version: '3.4'

services:

  ### Node ##################################
  node:
    container_name: todo_app-node
    build:
      context: ../
      dockerfile: docker/node/Dockerfile
      target: dev
    ports:
      - "${NODE_PORT}:3000"
    volumes:
      - ../:/app
      - node_modules:/app/node_modules

  ### MongoDB ##############################################
  mongo:
    container_name: todo_app-mongo-db
    build: ./mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - db:/data/db

volumes:
  node_modules:
  db: